test: test1.c test2.c test3.c test4.c test5.c
	gcc -Wall test1.c uvm.a -lpthread -o test1
	gcc -Wall test2.c uvm.a -lpthread -o test2
	gcc -Wall test3.c uvm.a -lpthread -o test3
	gcc -Wall test4.c uvm.a -lpthread -o test4
	gcc -Wall test5.c uvm.a -lpthread -o test5 -w

clean:
	rm test1 test2 test3 test4 test5